### ISSUE TITLE
[Group Package] 1 group include 3 billable metrics => push event => not generate charge

### ISSUE THREAD

**Issue by anhdtm2806** [Pressingly/lagu-api#51]
**Describe the bug**
Plan has 1 group (4 articles & 5GB & 5 minutes) => push event => not charge

**Pre-condition**
Plan A has 1 group including billable metrics: 4 articles & 5GB & 5 minutes - 4$

**To Reproduce**
1. Assign plan A to customer X
2. Push event in the 1st time (by sending "Add event" API in Postman) with:
      "code": "4_articles",
      "properties": {"storage": 2} 
3. Go to Invoices tab of customer X to check generating a new invoice
4. Not generate any new invoice

**Expected behavior**
Generating a new invoice with charge = 4$

**Screenshots**
https://www.loom.com/share/134a77bb43114ec4b52b3c435b77a268?sid=2b4bbf97-ad5a-4a7b-ba12-7ed9387e8e62

**Notes**
When push event with this information => also not generate a new charge
     

>  "code": "5gb",

     

>  "properties": {"5gb": 2}

**Comment by TronTram** [comment]
Still get an error when trying to post an event as in the image below.
![image](https://github.com/Pressingly/lagu-api/assets/45629756/58fa625e-cfc6-48a6-9565-fe52c7d1733e)

**Comment by anhdtm2806** [comment]
Test OK
